ci: Pin nightly toolchain in asm-test
```
thread 'test' (44984) panicked at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/asmtest-0.1.13/src/objdump.rs:61:20:
called `Result::unwrap()` on an `Err` value: process didn't exit successfully: `docker run --rm --init --mount type=bind,source=/home/runner/work/atomic-maybe-uninit/atomic-maybe-uninit/target/aarch64-unknown-linux-gnu/release/deps,target=/home/runner/work/atomic-maybe-uninit/atomic-maybe-uninit/target/aarch64-unknown-linux-gnu/release/deps,readonly --workdir /home/runner/work/atomic-maybe-uninit/atomic-maybe-uninit/target/aarch64-unknown-linux-gnu/release/deps --network=none --cap-drop=all --security-opt=no-new-privileges --read-only --user 1001:1001 ghcr.io/taiki-e/objdump@sha256:07e9b142237da061832dc6954fd51c86f2fa6916c5711f09d6b1d5edea408312 llvm-objdump -Cd --disassembler-color=off /home/runner/work/atomic-maybe-uninit/atomic-maybe-uninit/target/aarch64-unknown-linux-gnu/release/deps/asm_test-f48d0db57472d56e.o` (exit status: 125)
--- stderr
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /home/runner/work/atomic-maybe-uninit/atomic-maybe-uninit/target/aarch64-unknown-linux-gnu/release/deps

Run 'docker run --help' for more information
```