ci: Temporarily disable loongarch64 test on stable
```
qemu: uncaught target signal 4 (Illegal instruction) - core dumped
error: test failed, to rerun pass `--lib`

Caused by:
  process didn't exit successfully: `CARGO=/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo CARGO_MANIFEST_DIR=/home/runner/work/atomic-maybe-uninit/atomic-maybe-uninit CARGO_MANIFEST_PATH=/home/runner/work/atomic-maybe-uninit/atomic-maybe-uninit/Cargo.toml CARGO_PKG_AUTHORS='' CARGO_PKG_DESCRIPTION='Atomic operations on potentially uninitialized integers.
  ' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE='Apache-2.0 OR MIT' CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=atomic-maybe-uninit CARGO_PKG_README=README.md CARGO_PKG_REPOSITORY='https://github.com/taiki-e/atomic-maybe-uninit' CARGO_PKG_RUST_VERSION=1.59 CARGO_PKG_VERSION=0.3.8 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=3 CARGO_PKG_VERSION_PATCH=8 CARGO_PKG_VERSION_PRE='' LD_LIBRARY_PATH='/home/runner/work/atomic-maybe-uninit/atomic-maybe-uninit/target/loongarch64-unknown-linux-gnu/debug/deps:/home/runner/work/atomic-maybe-uninit/atomic-maybe-uninit/target/loongarch64-unknown-linux-gnu/debug:/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-linux-gnu/lib:/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib:/usr/local/target/usr/lib64:/usr/local/loongarch64-unknown-linux-gnu/lib:' OUT_DIR=/home/runner/work/atomic-maybe-uninit/atomic-maybe-uninit/target/loongarch64-unknown-linux-gnu/debug/build/atomic-maybe-uninit-06b69bb9f3ce9e61/out qemu-loongarch64 /home/runner/work/atomic-maybe-uninit/atomic-maybe-uninit/target/loongarch64-unknown-linux-gnu/debug/deps/atomic_maybe_uninit-5a29707025618f9f` (signal: 4, SIGILL: illegal instruction)
++ s=101
++ printf '%s\n' 'test.sh:16: `"$@"` exit with 101'
test.sh:16: `"$@"` exit with 101
++ exit 101
test.sh:17: `( set -x; "$@" )` exit with 101
test tests::test_atomic_i16::stress_compare_exchange ...
```