Avoid unexpected_cfgs error to feature set by clippy
```
error: unexpected condition value `cargo-clippy` for condition name `feature`
  |
  = note: `-D unexpected-cfgs` implied by `-D warnings`
  = help: was set with `--cfg` but isn't in the `--check-cfg` expected values
```