ci: Pin cortex-m-rt in no-std test on Rust 1.74
```
error: failed to download replaced source registry `crates-io`

Caused by:
  failed to parse manifest at `/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cortex-m-rt-macros-0.7.6/Cargo.toml`

Caused by:
  `resolver` setting `3` is not valid, valid options are "1" or "2"
```