Apply clippy to doctest
https://github.com/taiki-e/github-actions/commit/96af4dc51482b761c058fdc8ef3a80b44a18e51f

```
error[E0133]: call to unsafe function `std::intrinsics::transmute` is unsafe and requires unsafe block
   --> src/lib.rs:503:27
    |
503 |     let mut current_raw = mem::transmute::<Test, MaybeUninit<u32>>(current);
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call to unsafe function
    |
    = note: consult the function's documentation for information on how to avoid undefined behavior
note: an unsafe function restricts its caller, but its body is safe by default
   --> src/lib.rs:498:1
    |
498 | / unsafe fn atomic_compare_exchange(
499 | |     v: &AtomicMaybeUninit<u32>,
500 | |     mut current: Test,
501 | |     new: Test,
502 | | ) -> Result<Test, Test> {
    | |_______________________^
    = note: for more information, see <https://doc.rust-lang.org/edition-guide/rust-2024/unsafe-op-in-unsafe-fn.html>
    = note: requested on the command line with `-D unsafe-op-in-unsafe-fn`

error[E0133]: call to unsafe function `std::intrinsics::transmute` is unsafe and requires unsafe block
   --> src/lib.rs:504:19
    |
504 |     let new_raw = mem::transmute::<Test, MaybeUninit<u32>>(new);
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call to unsafe function
    |
    = note: consult the function's documentation for information on how to avoid undefined behavior
    = note: for more information, see <https://doc.rust-lang.org/edition-guide/rust-2024/unsafe-op-in-unsafe-fn.html>

error[E0133]: call to unsafe function `std::intrinsics::transmute` is unsafe and requires unsafe block
   --> src/lib.rs:513:32
    |
513 |                 let previous = mem::transmute::<MaybeUninit<u32>, Test>(previous_raw);
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call to unsafe function
    |
    = note: consult the function's documentation for information on how to avoid undefined behavior
    = note: for more information, see <https://doc.rust-lang.org/edition-guide/rust-2024/unsafe-op-in-unsafe-fn.html>

error: adding items after statements is confusing, since items exist from the start of the scope
   --> src/lib.rs:489:1
    |
489 | / use std::{
490 | |     mem::{self, MaybeUninit},
491 | |     sync::atomic::Ordering,
492 | | };
    | |__^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#items_after_statements
    = note: `-D clippy::items-after-statements` implied by `-D clippy::pedantic`
    = help: to override `-D clippy::pedantic` add `#[allow(clippy::items_after_statements)]`

error: adding items after statements is confusing, since items exist from the start of the scope
   --> src/lib.rs:490:5
    |
490 |     mem::{self, MaybeUninit},
    |     ^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#items_after_statements

error: adding items after statements is confusing, since items exist from the start of the scope
   --> src/lib.rs:490:11
    |
490 |     mem::{self, MaybeUninit},
    |           ^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#items_after_statements

error: adding items after statements is confusing, since items exist from the start of the scope
   --> src/lib.rs:490:17
    |
490 |     mem::{self, MaybeUninit},
    |                 ^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#items_after_statements

error: adding items after statements is confusing, since items exist from the start of the scope
   --> src/lib.rs:491:5
    |
491 |     sync::atomic::Ordering,
    |     ^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#items_after_statements

error: adding items after statements is confusing, since items exist from the start of the scope
   --> src/lib.rs:493:1
    |
493 | use atomic_maybe_uninit::AtomicMaybeUninit;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#items_after_statements

error: adding items after statements is confusing, since items exist from the start of the scope
   --> src/lib.rs:496:1
    |
496 | struct Test(u8, u16);
    | ^^^^^^^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#items_after_statements
```